### ISSUE TITLE
What does this mod provide?

### ISSUE THREAD

**Issue by ghost** [Ficklampan/TinyMod#1]
Hello,
I've just found your mod,
and I'm wondering what does it do,
not a modder or a java dev by any means but
i saw in the source something about optifine capes and shaders,
can you please clarify
thank you,
have a nice day

**Comment by ghost** [comment]
After using the mod I noticed that the movement broke and it's now diectional also player animations broke and found a shaders tab which is interesting,do optifine shaders work?

**Comment by EdvinVikstrom** [comment]
i have created a 'readme' with what the mod can do.
Shaders is not done and will explode the game:)
and the player animation problem is from the FastMath option

**Comment by ghost** [comment]
thanks for the help
