### ISSUE TITLE
Don't compete with a rendering engine

### ISSUE THREAD

**Issue by Madis0** [Ficklampan/TinyMod#5]
The readme says
> Faster Maths

while the options have

> Tiny Renderer

and 

> Fast Math

(though both crossed right now).

But I suggest, for the sake of Fabric and the open source community - please do not compete with a new, speed-optimizing rendering engine, instead co-operate to make your mod work well with [Sodium](https://github.com/jellysquid3/sodium-fabric) and/or [Canvas Renderer](https://github.com/grondag/canvas/issues). I think the community could create great open alternatives to Optifine if they work together 🙂

**Comment by EdvinVikstrom** [comment]
The tiny renderer and fast math is very buggyy.
You can enable it in the `tiny-mod.txt`

**Comment by Madis0** [comment]
I meant that maybe instead of working on those at all you encourage other developers' mods for optimization instead and limit this mod to graphics additions.

**Comment by EdvinVikstrom** [comment]
yes that sounds very good:)) im gonna do that;)
