### ISSUE TITLE
Requires Cotton Client Commands

### ISSUE THREAD

**Issue by Madis0** [Ficklampan/TinyMod#9]
For TinyMod 0.0.2 I am getting this message from Fabric Loader:
![error](https://user-images.githubusercontent.com/8611110/87796483-172e3880-c852-11ea-9f2d-66db696acd62.png)
[I downloaded the latest, 0.4.2](https://www.curseforge.com/minecraft/mc-mods/cotton-client-commands) and placed it next to TinyMod in mods folder, but am still getting the same error. Perhaps you need to bundle it in the jar?

**Comment by EdvinVikstrom** [comment]
hmmm im gonna look into that

**Comment by EdvinVikstrom** [comment]
fixed
